#pragma once



namespace vve {

	enum VeJobLabel {
		VE_JOB_LABEL_SYSENG_GAMELOOP2,
		VE_JOB_LABEL_SYSENG_COMPUTEONEFRAME2_START,
		VE_JOB_LABEL_SYSENG_COMPUTEONEFRAME2,
		VE_JOB_LABEL_VETABLE_SWAPTABLES
	};

	inline std::map<VeJobLabel, std::string> g_job_labels = {
		{ VeJobLabel::VE_JOB_LABEL_SYSENG_GAMELOOP2, "VE_JOB_LABEL_SYSENG_GAMELOOP2" },
		{ VeJobLabel::VE_JOB_LABEL_SYSENG_COMPUTEONEFRAME2_START, "VE_JOB_LABEL_SYSENG_COMPUTEONEFRAME2_START" },
		{ VeJobLabel::VE_JOB_LABEL_SYSENG_COMPUTEONEFRAME2, "VE_JOB_LABEL_SYSENG_COMPUTEONEFRAME2" },
		{ VeJobLabel::VE_JOB_LABEL_VETABLE_SWAPTABLES, "VE_JOB_LABEL_VETABLE_SWAPTABLES" }

	};


};

