#version 450

layout (binding = 0, rgba8) uniform readonly image2D inputImage;
layout (binding = 1, rgba8) uniform writeonly image2D outputImage;

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

void main() {
	//vec4 pixel = vec4(0.7, 0.1, 0.1, 0.0);
      vec4 pixel = imageLoad(inputImage,  ivec2(gl_GlobalInvocationID.xy));
	imageStore(outputImage, ivec2(gl_GlobalInvocationID.xy), pixel);
}
