#define VVE_MAX_SCENE_TEXTURES 64
#define VVE_MAX_SHADOWED_SPOT_LIGHTS 10
#define VVE_MAX_SHADOWED_POINT_LIGHTS 10
#define VVE_MAX_DIRECTIONAL_LIGHTS 10
#define VVE_NUM_SHADOW_CASCADES 4
#define VVE_SHADOW_MAP_RESOLUTION 1024
#define VVE_NO_TEXTURE 0xFFFFFFFFu
#define VVE_MATERIAL_BINDING 5
